# Generated by Django 3.0.8 on 2020-07-22 16:41

from django.db import migrations, models
import shortener.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0004_auto_20200721_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kirrurl',
            name='url',
            field=models.CharField(max_length=120, validators=[shortener.validators.url_validator, shortener.validators.dotcom_validator]),
        ),
    ]
